preconnect:
  - https://gcore.jsdelivr.net
  - https://unpkg.com

inject:
  head:
    - <link rel="apple-touch-icon" sizes="180x180" href="/assets/xaoxuu/favicon/apple-touch-icon.png">
    - <link rel="icon" type="image/png" sizes="32x32" href="/assets/xaoxuu/favicon/favicon-32x32.png">
    - <link rel="icon" type="image/png" sizes="16x16" href="/assets/xaoxuu/favicon/favicon-16x16.png">
    - <link rel="manifest" href="/assets/xaoxuu/favicon/site.webmanifest">
    - <link rel="shortcut icon" href="/assets/xaoxuu/favicon/favicon.ico">
    - <meta name="theme-color" content="#f8f8f8">

logo:
  icon: /assets/icon.svg
  title: Stellar
  subtitle: '每个人的独立博客 | Designed by xaoxuu'
menubar:
  items: 
    - id: post
      theme: '#1BCDFC'
      icon: solar:documents-bold-duotone
      title: 博客
      url: /
    - id: topic
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 项目
      url: /wiki/
    - id: explore
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 探索
      url: /explore/
    - id: social
      theme: '#F44336'
      icon: solar:chat-square-like-bold-duotone
      title: 社交
      url: /friends/

site_tree:
  home:
    sidebar: starter, welcome, recent
  index_blog:
    sidebar: starter, welcome, recent
  index_topic:
    menu_id: topic
  topic:
    menu_id: topic

article:
  share: [wechat, weibo, email, link]


style:
  header_prefix:
    h2: ''
    h3: ''
  text-align: justify
  smooth_scroll: false
  codeblock:
    scrollbar: 0px
  font-size:
    body: 1rem
  font-family:
    logo: 'system-ui, "Microsoft Yahei", "Segoe UI", Arial, sans-serif'
    body: 'system-ui, "Microsoft Yahei", "Segoe UI", Arial, sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, monospace, sans-serif'


comments:
  service: giscus
  comment_title: 快来参与讨论吧~
  lazyload: true
  giscus:
    src: https://giscus.app/client.js
    data-repo: mariozhujian/blog-comments
    data-repo-id: R_kgDOTUO3hw
    data-category: Announcements
    data-category-id: DIC_kwDOTUO3h84DA4xV
    data-mapping: title
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

plugins:
  copycode:
    enable: true
    default_text: 复制
    success_text: 已复制
    toast: 复制成功
